In [2]:
import numpy as np
##https://numpy.org/
 

 

## linspace
 start ve stop arasinda  araliklari (esit ) olma sartiyla n sayi     olusturur

In [3]:
np.linspace(0,12,3)  ## start stop  dizi icerecegi eleman sayisi

array([ 0.,  6., 12.])

## random :
rasgele bazi degerler cikariyor ve cikardigi degerler Noramal dagilima uygun degerler olmasina calisiyor(Kullandigi Yapi standart distiribisyon)


In [26]:
np.random.randn(4)# numpy dizisi dondurur bize randn

# print("--------------------")
# np.random.randn(4,4) #two dimesionalArrays da olusturabiliriz

array([ 0.09175024,  0.9716568 , -0.28731887, -0.1821281 ])

In [29]:
#! tek bir deger dondurmek ise ve Integer deger dondurmesi
np.random.randint(20) 
np.random.randint(1,30,5) ##start stop_dahil_degil 3.kac_rakam dondurmesini istiyoruz 

array([ 4,  6, 18,  7,  1])

In [7]:
#start ve stop arasinda  stop haric  olma sartiyla ntane Rasgele_sayi(int_tipinden) olusturur
np.random.randint(2,12,10) 

array([ 2, 10,  7,  5, 11,  3,  8,  2,  4,  3])

## arange :

Numpy dizisi olusturuyor sirali bir sekilde 1. bslng  2.bitis 3.step

In [8]:
np.arange(0,39,7) ## buradaki 3. argument StepSize eleman sayisi degil 

array([ 0,  7, 14, 21, 28, 35])

In [13]:
np.arange(5)


array([0, 1, 2, 3, 4])

## eye  
: birincil matrisleri olusturuyor 


In [10]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## nummpy_dizi_methods

### reshape dizileri sekillendirmek icin kullanilir 
### max en buyuk deger geri dondurur 
### min en kucuk sayi da geri dondurur
### argmax en buyuk sayinin indexini getirir argmin de ayni sekilde 

### Attribute de var dizilerin .shape  dizi hangi sekile sahip oldugunu  gosterir

In [31]:
myList=np.arange(30,70)
#myList
myList.reshape(4,10)   ##diziyi sekillendirmek icin kullanilir 


array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [12]:
x=myList.max()
x

68

In [32]:
myList.argmax()

39

## Matrix : 2 boyutlu diziler 



In [22]:
benimMatris= np.array([5,8])

In [23]:
print(benimMatris)

[5 8]


In [45]:
benimList=list(range(0,24))

In [46]:
mm=np.array(benimList)
mm

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
mm= mm.reshape(6,4)
mm

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [49]:
mm[0:,0] ##0.satirdan itibaren  tum sifirinci indexleri getir 

array([ 0,  4,  8, 12, 16, 20])

In [48]:
mm[[0,2,4]]## 0. 2. ve 4. satirlari getiriyo bir liste seklinde (Fancy index )

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

## Zeros :
sifirlarla dolur bir dizi

In [9]:
np.zeros((2,2)) ##satir sonra sutun sayisi 
np.ones(9) ## birleden olusan diziler olusturuyor

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

## pythonNumpy daki slice olayi 
numpy dizilerinde slicing ile yeni bir dizi olusturdugumuzda  bu yeni olusturulan diziler uzerinde degisiklik yaptigim zaman bu degisiklikler ana diziyi etkileyecek object pointer matigiyla dusun yani burada sadece pointerler bir index itibaren atiyo o yuzden tabi degisiklik olacaktir  . degisiklik olmamasi icin .copy() methodu kullanmam lazim

In [37]:
benimDizim=np.arange(0,20)
benimDizim[3:8] ##stop index dahil degil 
benimDizim[3:8]=-1 ## belli aralikta bulunan degerleri degistirebiliriz
benimDizim

array([ 0,  1,  2, -1, -1, -1, -1, -1,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### operasyonlar 

In [60]:
yeniBirDizi=np.random.randint(1,100,20)
yeniBirDizi



array([92,  8, 21, 25, 68, 60, 46, 63, 31, 92, 85, 63, 63, 11, 37, 34, 24,
       52, 83, 17])

In [61]:
sonucdizi=yeniBirDizi>24 ## boolean bir dizi 
sonucdizi

array([ True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True, False])

In [63]:
#filter dusun 
yeniBirDizi[sonucdizi]  #tekrar varsa getirmiyor set sanki
# type(yeniBirDizi[sonucdizi])

numpy.ndarray

In [ ]:
# np.sqrt()
# iki dizi bir birine ekleme index index gider tum hesaplamalarda 